countdown-lb:
  ports:
  - 8000:80
  labels:
    io.rancher.scheduler.affinity:host_label: lb=true
    io.rancher.loadbalancer.target.countdown-app: '80'
  restart: always
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
  links:
  - countdown-app
countdown-app:
  restart: always
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: flaccid/countdown_example:latest
  stdin_open: true
